---
- hosts: minion1
  tasks:
        - name: "install git"
          yum: name="git" state="present"
        - name: "install tomcat"
          yum: name="tomcat" state="present"
        - name: "install tomcat admin packages"
          yum: name={{item}} state="present"
          with_items:
                       - tomcat-webapps
                       - tomcat-admin-webapps
        - name: "start tomcat service"
          service: name="tomcat" state="restarted"
        - name: copy jenkins war file
          copy: src="/vagrant/jenkins.war" dest="/var/lib/tomcat/webapps"
        - name: restart tomcat
          service: name="tomcat" state="restarted"

          
